### PR TITLE
Fix highlight.js background when using custom theme

### LINKED ISSUE #76: Missing background on Highlight.js themes
For most Highlight.js themes background is pretty much part of the theme. However, background is currently missing with `vmd`.

npm v browserify readme |vmd --highlight-theme=solarized-dark

should be:

previous + ad-hoc hacks

Some themes are really ugly without a proper background:

npm v browserify readme |vmd --highlight-theme=far

Fixing this issue requires [applying a `hljs` class](https://github.com/isagalaev/highlight.js/blob/80d5b7299dc8cedc8901e03bdad2b752341cc344/src/styles/solarized-dark.css#L7-L13) on `pre` element or containing `div`. Unfortunately, it isn't that simple because of [a higher-specificity rule](https://github.com/sindresorhus/github-markdown-css/blob/033e86abcb007c3f103b33324945f5ce845617cf/github-markdown.css#L477-L484) in `github-markdown-css`. I don't really know how to solve that. Any ideas?

### PR DESCRIPTION
**Pull request by maxkueng**
Fixes #76

### CODE REVIEW

File: main/styles.js [hunk 1]
```diff
@@ -23,6 +23,7 @@ exports.getHighlightTheme = function (theme) {
 
   try {
     return fs.readFileSync(themePath, 'utf-8')
+      .replace(/([^;]+);/g, '$1 !important;')
```
Comment (eush77) [inline main/styles.js]: According to [spec](https://www.w3.org/TR/css-syntax-3/#consume-a-list-of-declarations) it seems that a semicolon is just a delimiter between CSS declarations, so this doesn't work in general for a last declaration in a block. And also semicolons may appear in comments (which is fine) and strings like font names or urls (probably not).

Maybe this transform wasn't really supposed to be generic but since it is applied to a Highlight.js stylesheet which can be either one of many built-in themes or even potentially user-defined (with `--highlight-stylesheet`), I'd say it's better to stay correct.

Have you tried other modules for that? For example, [postcss-safe-important](https://github.com/crimx/postcss-safe-important) seems really easy to integrate with:

```js
var postcss = require('postcss');
var important = require('postcss-safe-important');

postcss(important).process('foo { width: 100px; color: red }').css
//=> 'foo { width: 100px !important; color: red !important }'
```

**Comment by eush77** [comment]
It does work for me. Thanks! :+1:

**Comment by maxkueng** [comment]
@eush77 Good catch about the semicolons! I didn't even think about this. I have now changed it so that it uses postcss. 

It's a bit crazy that we have to use two new dependencies for a feature that very few people use but I guess it's the cleanest solution. Maybe we have to do more CSS transformation in the future.

Thanks a lot for helping out and giving feedback!

**Comment by maxkueng** [comment]
vmd@1.25.1 contains the fix and is now available on npm. Get it while it's hot :fire:!
